name: Flutter CI Action, create build for manual testing       # То, что будет отображаться во вкладке Actions
on: push

jobs:                                                          # Делаем сборку для Android
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        channel: 'stable'
    - run: flutter --version                                   # Выведет текущую версию Flutter
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
    - name: collect apk artifacts                             
      uses: actions/upload-artifact@v3
      with:
        name: Download Android version
        # Path to the release files
        path: build/app/outputs/flutter-apk/app-release.apk


  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        architecture: x64
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
    - name: collect ipa artifacts                             
      uses: actions/upload-artifact@v3
      with:
        name: Download iOS version
        # Path to the release files
        path: /Users/runner/work/simplecryptodata/simplecryptodata/build/ios/iphoneos/Runner.app