name: Flutter CI Action, create build for manual testing       # То, что будет отображаться во вкладке Actions
on: push

jobs:                                                          # Делаем сборку для Android
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        channel: 'stable'
    - run: flutter --version                                   # Выведет текущую версию Flutter
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle

  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        architecture: x64
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign